apiVersion: v1
kind: Namespace
metadata:
  name: example-2
---
apiVersion: v1
kind: Service
metadata:
  name: app
spec:
  type: LoadBalancer
  selector:
    app: example-2
  ports:
    - port: 80
      targetPort: 80
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: example-2
spec:
  selector:
    matchLabels:
      app: example-2
  replicas: 2
  template:
    metadata:
      labels:
        app: example-2
    spec:
      containers:
      - name: example-2
        image: example-2:latest
        ports:
        - containerPort: 80
