apiVersion: v1
kind: Namespace
metadata:
  name: example-1
---
apiVersion: v1
kind: Service
metadata:
  name: app
spec:
  type: LoadBalancer
  selector:
    app: example-1
  ports:
    - port: 80
      targetPort: 80
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: example-1
spec:
  selector:
    matchLabels:
      app: example-1
  replicas: 2
  template:
    metadata:
      labels:
        app: example-1
    spec:
      containers:
      - name: example-1
        image: example-1:latest
        ports:
        - containerPort: 80
